[package]
name = "rust-bin2png-test"
version = "0.1.0"
authors = ["Sophie 'Sharky' Schumann <sharky@sharky.pw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.4"
indicatif = "0.14.0"